### ISSUE TITLE
readme.md mentioning of a "patched" game

### ISSUE THREAD

**Issue by MattMcFarland** [openplanet-nl/turbo-scripts#1]
Hello,

First thanks so much for sharing these scripts with the world! 
In reference to your readme:

> If you have the ability to run a custom menu script (you need a patched game), you can run these customized scripts in the game.

How does one get the ability to run a custom menu script?   I was googling but I couldn't find any information for doing it.  My initial hope was that I'd run into a forum post or something with more instructions but saw nothing.  Could you point me int he right direction??  Thanks :D

**Comment by codecat** [comment]
Since we're working together with Nadeo to get Openplanet (as a scripting platform) released publicly, I've been asked not to post any details on how to patch the game to do this on a casual game like Turbo.

However, if you have the technical knowledge, this might help you; the game will load the `menu` -> `manialink` url attribute from the [ManiaPlanetTitle.xml](https://github.com/openplanet-nl/turbo-scripts/blob/master/ManiaPlanetTitle.xml) file, which you will have to point to your own file on disk instead.

**Comment by MattMcFarland** [comment]
Cool!  openplanet sounds awesome, I just released a VS Code extension this weekend for the ManiaScript language!  https://github.com/MattMcFarland/vscode-maniascript

**Comment by codecat** [comment]
Nice one! 👍
